#!/bin/bash

find src -name "*.h"  -exec clang-format -i {} \;
find src -name "*.cc"  -exec clang-format -i {} \;
find samples -name "*.h"  -exec clang-format -i {} \;
find samples -name "*.cc"  -exec clang-format -i {} \;
find include -name "*.h"  -exec clang-format -i {} \;

